name: Push container image to test repository
on: 
  workflow_dispatch:

jobs:
  call:
    uses: ysuika/acore-cicd-templates/.github/workflows/push-to-nonprod.yml@main
    with:
      test-image-repo: ghcr.io/ysuika/sdv-sdk-test
